#undef PRODUCT
#define PRODUCT "Pejer Dilemma"
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define SPLIT_ACTIVITY_ENABLE

#define RGB_DISABLE_WHEN_USB_SUSPENDED
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define CIRQUE_PINNACLE_TAP_ENABLE
#define AUTO_MOUSE_TIME 250
//#define I2C1_CLOCK_SPEED 400000
//#define I2C1_DUTY_CYCLE FAST_DUTY_CYCLE_16_9
#ifdef OLED_ENABLE
#    define OLED_DISPLAY_128X64
#    define SPLIT_OLED_ENABLE
#    define SPLIT_TRANSPORT_MIRROR
#    define SPLIT_LAYER_STATE_ENABLE
#    define SPLIT_MODS_ENABLE


    /* Mapping I2C2 for OLED
     * THESE ARE THE VAULES I THINK WE MIGHT HAVE TO FIX
     * */
    // #define I2C1_SCL_PIN B10
    // #define I2C1_SDA_PIN B11
    // #define I2C_DRIVER I2CD2

#endif

